#define IDI_ICON1 101
#define ID_BROWSE_BUTTON 102
#define ID_START_BUTTON 103
#define ID_STOP_BUTTON 104
#define ID_ADD_BUTTON 105
#define ID_REMOVE_BUTTON 106
#define ID_SETTINGS 107
#define ID_ABOUT 108
#define ID_FILE_EXIT 109  // **Added Exit ID**
#define ID_HELP_ABOUT 110 // **Added About ID**
#define ID_LISTBOX 111
#define ID_OUTPUT_TYPE 121

// Settings Window IDs
#define ID_TMP_FOLDER_BROWSE 112
#define ID_OUTPUT_FOLDER_BROWSE 113
#define ID_WINRAR_PATH_BROWSE 114
#define ID_SEVEN_ZIP_PATH_BROWSE 115
#define ID_IMAGEMAGICK_PATH_BROWSE 116

#define ID_IMAGE_QUALITY_SLIDER 117

#define ID_SAVE_SETTINGS 118

#define IDC_ABOUT_BMP  119
#define IDC_ABOUT_OK   120
