#define IDI_VERSION_INFO 1
#define IDI_ICON1 101

#define ID_BROWSE_BUTTON 102
#define ID_START_BUTTON 103
#define ID_STOP_BUTTON 104
#define ID_ADD_BUTTON 105
#define ID_REMOVE_BUTTON 106
#define ID_ADD_FOLDER_BUTTON 107
#define ID_SETTINGS 108
#define ID_ABOUT 109
#define ID_FILE_EXIT 110  // **Added Exit ID**
#define ID_HELP_ABOUT 111 // **Added About ID**
#define ID_INSTRUCTIONS_HELP 112
#define ID_CHECK_FOR_UPDATE 113 // **Added Check for Update ID**
#define ID_LISTBOX 114
#define ID_OUTPUT_TYPE 115
#define ID_IMAGE_TYPE 116
#define ID_OPEN_IN_TMP_FOLDER_BUTTON 117
#define ID_OPEN_IN_OUTPUT_FOLDER_BUTTON 118

// Settings Window IDs
#define ID_TMP_FOLDER_BROWSE 130
#define ID_OUTPUT_FOLDER_BROWSE 131
#define ID_WINRAR_PATH_BROWSE 132
#define ID_SEVEN_ZIP_PATH_BROWSE 133
#define ID_IMAGEMAGICK_PATH_BROWSE 134
#define ID_MUTOOL_PATH_BROWSE 135
#define ID_IMAGE_QUALITY_SLIDER 136
#define ID_IMAGE_RESIZE_TO 137
#define ID_IMAGE_KEEP_ASPECT_RATIO 138
#define ID_IMAGE_ALLOW_UPSCALING 139

#define ID_WEBP_QUALITY_SLIDER 150
#define ID_WEBP_METHOD 151

#define ID_SAVE_SETTINGS 190


#define IDB_BUTTON_PLUS 201
#define IDB_BUTTON_MINUS 202
#define IDB_BUTTON_ADD 203
#define IDB_BUTTON_ADD_FOLDER 204
#define IDB_BUTTON_START 205
#define IDB_BUTTON_STOP 206
#define IDB_OPEN_IN_FOLDER 207

#define IDC_ABOUT_BMP  301
#define IDC_ABOUT_OK   302
#define IDC_ABOUT_ICON 303

#define IDC_INSTRUCTIONS_TEXT 401
#define IDC_INSTRUCTIONS_OK   402

// Menu
#define IDB_INSTRUCTIONS_ICON 501
